export const ERROR_INVALID_SCHEMA_MISSING_PROPERTIES =
  'ERROR_INVALID_SCHEMA_MISSING_PROPERTIES';
export const ERROR_INVALID_SCHEMA_INVALID_PROPERTY_TYPE =
  'ERROR_INVALID_SCHEMA_INVALID_PROPERTY_TYPE';
export const ERROR_INVALID_SCHEMA_INVALID_PROPERTY_NAME =
  'ERROR_INVALID_SCHEMA_INVALID_PROPERTY_NAME';
export const ERROR_SCHEMA_NOT_FOUND = 'ERROR_SCHEMA_NOT_FOUND';
export const ERROR_SCHEMA_REGISTER_FAILED = 'ERROR_SCHEMA_REGISTER_FAILED';
